functional:
  - Сайт должен иметь возможность регистрации нового пользователя
  - У пользователя должна быть возможность авторизоваться
  - Сайт должен иметь возможность переключения языков
  - Пользователь может менять языки программирования при решении задач
  - У пользователя должна быть возможность пробной игры в неавторизованном режиме
  - Во время игры пользователь может проверить свое решение, изменить решение
  - Во время игры пользователь видит таймер окончания решения задачи
  - У пользователей есть возможность писать в чат во время игры
non-functional:
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
implicit:
  - При отсутствии интернет соединения должно отображаться стандартное текстовое сообщение об отсутствии подключения
  - При авторизации или регистрации должна работать валидация данных
