functional:
  - Сайт должен иметь возможность регистрации нового пользователя +
  - У пользователя должна быть возможность авторизоваться +
  - Сайт должен иметь возможность переключения языков +
  - Пользователь может менять языки программирования при решении задач +
  - У пользователя должна быть возможность пробной игры в неавторизованном режиме +
  - Во время игры пользователь может проверить свое решение, изменить решение +
  - Во время игры пользователь видит таймер окончания решения задачи
  - У пользователей есть возможность писать в чат во время игры
  - Решенная задача или нет должна отображаться в списках
  - Выигрывает тот игрок, что решил задачу
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен иметь адаптивную верстку при просмотре веб-страницы на компьютерах и на мобильных устройствах
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - При отсутствии интернет соединения должно отображаться стандартное текстовое сообщение браузера об отсутствии подключения
  - При авторизации и регистрации должна работать валидация данных, которые вводит пользователь
